
project_id = "vsgsagbpfclbuyqrepvf"

[api]
enabled = true
port = 8080
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 5432
shadow_port = 5431
major_version = 15

[studio]
enabled = true
port = 8082
api_url = "http://localhost"

[inbucket]
enabled = true
port = 8084

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[analytics]
enabled = false
port = 8085
vector_port = 8086
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = "supabase/gcloud.json"

[experimental]
[experimental.postgres_write_hook]
enabled = false

[functions.send-trainer-payment]
verify_jwt = false

[functions.check-column-exists]
verify_jwt = false
