import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { ArrowRight,BadgeCheck,Banknote,Bone,CalendarDays,Check,Clock3,Dog,ExternalLink,Footprints,Heart,Info,Mail,MapPin,PawPrint,Phone,ShoppingBag,Sparkles,ClipboardCheck } from "lucide-react";
import { InfoPack,PuppyCourse,formatLessonDates } from "./useInfoPackData";
import deltaLogoFallback from "@/assets/mckaynine_delta_long_2025.png";

const TRAINER="/images/puppy-registration/trainer-and-puppy.jpg";
const icons=[Dog,Bone,Heart,Footprints,Sparkles,PawPrint];
const tones=["bg-[#f2e7db] text-[#6d5947]","bg-[#e1f0eb] text-[#315f55]","bg-[#e6edf4] text-[#405b75]","bg-[#fbefd8] text-[#715c32]","bg-[#e9e5f5] text-[#554a76]","bg-[#e2f0eb] text-[#386259]"];
const money=(n:number)=>new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR",minimumFractionDigits:0}).format(n);
interface Props{packs:InfoPack[];activePack?:InfoPack;courses:PuppyCourse[];onSelectBranch:(id:string)=>void;onStart:()=>void}

function Title({icon:Icon,children,green=false}:{icon:typeof PawPrint;children:React.ReactNode;green?:boolean}){return <h2 className={cn("flex items-center gap-2.5 text-[17px] font-extrabold tracking-[-.02em] text-[#09294f]",green&&"text-[#315f55]")}><Icon className="h-[23px] w-[23px]" strokeWidth={1.8}/>{children}</h2>}
function TickList({items,compact=false}:{items:string[];compact?:boolean}){return <ul className={cn("mt-4 space-y-3",compact&&"mt-3 space-y-2")}>{items.map(item=><li key={item} className="flex items-start gap-2.5 text-[12px] leading-[1.35] text-[#263849]"><span className="mt-px grid h-[17px] w-[17px] shrink-0 place-items-center rounded-full border border-[#78b6a1] text-[#397863]"><Check className="h-2.5 w-2.5"/></span>{item}</li>)}</ul>}

function Hero({packs,activePack:p,courses,onSelectBranch,onStart}:Props&{activePack:InfoPack}){
 const year=courses[0]?new Date(courses[0].startTime).getFullYear():new Date().getFullYear();
 return <section className="relative min-h-[397px] overflow-hidden border-b border-[#dfe5e9] bg-[#faf7f1] lg:grid lg:grid-cols-[43.5%_56.5%]">
  <div className="relative z-10 flex flex-col justify-between px-[4.4%] py-7"><div><div className="mb-4 flex items-center gap-3"><img src={p.logo_url||deltaLogoFallback} onError={e=>{e.currentTarget.src=deltaLogoFallback}} alt={`McKaynine ${p.branch.name}`} className="h-[68px] w-auto max-w-[280px] object-contain mix-blend-multiply"/>{packs.length>1&&<select aria-label="Training branch" value={p.branch_id} onChange={e=>onSelectBranch(e.target.value)} className="rounded-full border border-[#d7dfe5] bg-white px-3 py-1.5 text-xs font-bold text-[#124f9e]">{packs.map(pack=><option key={pack.id} value={pack.branch_id}>{pack.branch.name}</option>)}</select>}</div><h1 className="max-w-[590px] text-[clamp(2.75rem,4.15vw,4rem)] font-extrabold leading-[.98] tracking-[-.045em] text-[#082b55]">{p.hero_heading}</h1><p className="mt-4 max-w-[550px] text-[17px] leading-relaxed text-[#3f4b55]">{p.hero_subheading}</p></div>
  <div className="mt-5 flex flex-wrap items-center gap-x-7 gap-y-3"><Button onClick={onStart} className="h-[58px] rounded-[10px] bg-[#0f5ad1] px-6 text-[17px] font-bold shadow-[0_8px_18px_rgba(15,90,209,.18)] hover:bg-[#0b4db8]">Start enrolment <ArrowRight className="ml-5 h-5 w-5"/></Button>{p.trust_lines.slice(0,2).map(line=><span key={line} className="flex max-w-[195px] items-center gap-2.5 border-l border-[#d9d4cb] pl-6 text-[11px] leading-snug text-[#313e49] first:border-0 first:pl-0"><BadgeCheck className="h-7 w-7 shrink-0 text-[#967f69]"/>{line}</span>)}</div></div>
  <div className="relative min-h-[330px] lg:absolute lg:inset-y-0 lg:right-0 lg:w-[66%]"><img src={TRAINER} alt="McKaynine trainer holding a puppy" className="absolute inset-0 h-full w-full object-cover object-[50%_31%]"/><div className="absolute inset-0 bg-gradient-to-r from-[#faf7f1] via-[#faf7f1]/10 to-transparent"/></div>
  <aside className="relative z-20 m-4 rounded-[18px] bg-white/95 p-4 shadow-[0_14px_40px_rgba(11,32,53,.2)] backdrop-blur lg:absolute lg:right-[2.6%] lg:top-[42px] lg:m-0 lg:w-[245px]"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-full bg-[#d9eae3] text-[#396656]"><CalendarDays className="h-6 w-6"/></span><h2 className="text-[17px] font-extrabold text-[#214f43]">{year} Class Dates</h2></div><p className="mt-4 flex gap-3 text-[13px] text-[#253541]"><Clock3 className="h-4 w-4"/>{p.venue_time}</p>{courses.slice(0,1).map(c=><p key={c.id} className="mt-4 flex gap-3 text-[13px] leading-[1.45] text-[#253541]"><CalendarDays className="mt-0.5 h-4 w-4 shrink-0"/><span>{formatLessonDates(c.dates)}</span></p>)}<p className="mt-4 flex gap-3 text-[13px] leading-[1.45] text-[#253541]"><MapPin className="mt-0.5 h-4 w-4 shrink-0"/>{p.venue_name}</p>{p.missed_class_note&&<p className="mt-4 rounded-xl bg-[#e3f1ec] p-3 text-[12px] leading-[1.4] text-[#24483f]"><strong>Missed the first class?</strong><br/>{p.missed_class_note.replace(/Missed the first class\??\s*/i,"")}</p>}</aside>
 </section>
}

function Middle({p,courses}:{p:InfoPack;courses:PuppyCourse[]}){const c=courses[0];const notes=p.start_notes.length?p.start_notes:[p.start_age_note,p.vaccination_note].filter(Boolean) as string[];return <section className="grid gap-4 px-[3.2%] py-3 lg:grid-cols-[1.52fr_.72fr_.75fr]">
 <div><h2 className="mb-2 text-[17px] font-extrabold text-[#0a2a50]">What we help with</h2><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-6">{p.help_with.map((item,i)=>{const Icon=icons[i%icons.length];return <div key={item} className="flex min-h-[164px] flex-col items-center rounded-[13px] border border-[#e3e7e9] bg-white px-2 py-3 text-center shadow-[0_2px_7px_rgba(16,40,65,.04)]"><span className={cn("grid h-[72px] w-[72px] place-items-center rounded-full",tones[i%tones.length])}><Icon className="h-9 w-9" strokeWidth={1.35}/></span><p className="mt-auto pb-1 text-[12px] font-medium leading-[1.25] text-[#1f2d39]">{item}</p></div>})}</div></div>
 <div className="rounded-[14px] bg-[#f5eee6] p-4"><Title icon={Banknote}>Course fees</Title>{c&&<div className="mt-4 space-y-2 text-[12px] text-[#263849]"><p>✓ &nbsp;6 lesson course: {money(c.courseFee)} per puppy</p><p>✓ &nbsp;Enrolment fee: {money(c.enrollmentFee)}</p></div>}<p className="mt-2 text-[12px] leading-snug text-[#263849]">✓ &nbsp;{p.fee_includes}</p>{p.discount_note&&<p className="mt-4 rounded-[10px] bg-[#ead7c1] px-3 py-2 text-[12px] font-medium leading-snug text-[#3b3026]">◇ &nbsp;{p.discount_note}</p>}</div>
 <div className="rounded-[14px] bg-[#edf4f1] p-4"><Title icon={CalendarDays} green>When can I start?</Title><TickList items={notes}/></div>
 </section>}

function Lower({p}:{p:InfoPack}){const before=p.before_enrol_notes.length?p.before_enrol_notes:[p.cutoff_note].filter(Boolean) as string[];return <section className="grid gap-3 px-[3.2%] pb-4 lg:grid-cols-[.72fr_1.02fr_.73fr_2fr]">
 <div className="rounded-[14px] border border-[#e0e5e8] p-4"><Title icon={ShoppingBag} green>What to bring</Title><TickList compact items={p.what_to_bring}/></div>
 <div className="rounded-[14px] border border-[#e0e5e8] p-4"><Title icon={ClipboardCheck}>Joining details</Title><TickList compact items={p.joining_steps}/>{p.banking_details&&<p className="mt-2 text-[11px] leading-snug text-[#263849]">✓ &nbsp;{p.banking_details}</p>}</div>
 <div className="rounded-[14px] border border-[#e0e5e8] p-4"><Title icon={Clock3}>Before you enrol</Title><TickList compact items={before}/>{p.weather_note&&<p className="mt-3 text-[11px] leading-snug text-[#263849]">{p.weather_note}</p>}<div className="mt-3 space-y-2 text-[11px] text-[#153d70]">{p.contact_phone&&<a className="flex gap-2" href={`tel:${p.contact_phone.replace(/\s/g,"")}`}><Phone className="h-3.5 w-3.5"/>{p.contact_phone}</a>}{p.contact_email&&<a className="flex gap-2" href={`mailto:${p.contact_email}`}><Mail className="h-3.5 w-3.5"/>{p.contact_email}</a>}</div></div>
 <div className="grid overflow-hidden rounded-[14px] border border-[#e0e5e8] sm:grid-cols-[.82fr_1.18fr]"><div className="p-4"><Title icon={MapPin}>Find us</Title><ol className="mt-3 space-y-1.5">{p.directions.map((step,i)=><li key={step} className="flex gap-2 text-[11px] leading-[1.25] text-[#263849]"><span className="grid h-[18px] w-[18px] shrink-0 place-items-center rounded-full bg-[#4f8dd8] text-[9px] font-bold text-white">{i+1}</span>{step}</li>)}</ol>{p.calls_note&&<p className="mt-3 rounded-lg bg-[#e6f0ff] p-2 text-[9px] leading-snug text-[#245897]"><Info className="mr-1 inline h-3.5 w-3.5"/>{p.calls_note}</p>}</div><div className="relative min-h-[245px] overflow-hidden bg-[#dfece2] before:absolute before:left-[-10%] before:top-[42%] before:h-4 before:w-[125%] before:-rotate-12 before:bg-white/80 before:content-[''] after:absolute after:left-[38%] after:top-[-15%] after:h-[140%] after:w-3 after:rotate-[28deg] after:bg-white/70 after:content-['']">{p.map_image_url&&<img src={p.map_image_url} onError={e=>{e.currentTarget.style.display="none"}} alt="" className="absolute inset-0 z-10 h-full w-full object-cover"/>}<MapPin className="absolute left-[56%] top-[34%] z-20 h-12 w-12 fill-[#1260cf] text-[#1260cf] drop-shadow-md"/>{p.map_link&&<Button asChild variant="outline" className="absolute bottom-3 right-3 z-20 h-11 rounded-[9px] border-2 border-[#1260cf] bg-white px-5 text-sm font-bold text-[#1260cf]"><a href={p.map_link} target="_blank" rel="noreferrer">Open in Maps <ExternalLink className="ml-3 h-4 w-4"/></a></Button>}</div></div>
 </section>}

export function PuppyInfoPack(props:Props){const p=props.activePack;if(!p)return null;return <div className="overflow-hidden rounded-[18px] border border-[#cfd8df] bg-white shadow-[0_14px_45px_rgba(23,46,70,.08)]"><Hero {...props} activePack={p}/><Middle p={p} courses={props.courses}/><Lower p={p}/><section className="mx-[3.2%] mb-3 flex flex-col items-start justify-between gap-4 rounded-[14px] bg-gradient-to-r from-[#eef5ff] to-[#f5f8fc] px-5 py-4 sm:flex-row sm:items-center"><div className="flex items-center gap-5"><span className="grid h-14 w-14 place-items-center rounded-[12px] bg-[#0f5ad1] text-white"><PawPrint className="h-8 w-8"/></span><div><h2 className="text-[24px] font-extrabold tracking-tight text-[#0a2a50]">Ready to get started?</h2><p className="text-[12px] text-[#344454]">Spots are limited to ensure personal attention for every puppy.</p></div></div><Button onClick={props.onStart} className="h-[54px] min-w-[285px] rounded-[9px] bg-[#0f5ad1] text-[17px] font-bold hover:bg-[#0b4db8]">Start enrolment <ArrowRight className="ml-auto h-5 w-5"/></Button></section></div>}
