// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsgsagbpfclbuyqrepvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzZ3NhZ2JwZmNsYnV5cXJlcHZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NTY2NTIsImV4cCI6MjA1ODEzMjY1Mn0.FnpdU39UlCOxGx8IYt4oMdRfT9nhyuXwYgqli0MsmtA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);